/******************************************************************************
* File Name: secure_keys.h
*
* Description: This file contains configuration parameters for the secure HTTP
* server and the server security keys such as server certificate, private key,
* and the root CA (certificate authority) to trust the client.
*
******************************************************************************
* Copyright (2020), Cypress Semiconductor Corporation.
******************************************************************************
* This software, including source code, documentation and related materials
* (“Software”), is owned by Cypress Semiconductor Corporation or one of its
* subsidiaries (“Cypress”) and is protected by and subject to worldwide patent
* protection (United States and foreign), United States copyright laws and
* international treaty provisions. Therefore, you may use this Software only
* as provided in the license agreement accompanying the software package from
* which you obtained this Software (“EULA”).
*
* If no EULA applies, Cypress hereby grants you a personal, nonexclusive,
* non-transferable license to copy, modify, and compile the Software source
* code solely for use in connection with Cypress’s integrated circuit products.
* Any reproduction, modification, translation, compilation, or representation
* of this Software except as specified above is prohibited without the express
* written permission of Cypress.
*
* Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT, IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Cypress
* reserves the right to make changes to the Software without notice. Cypress
* does not assume any liability arising out of the application or use of the
* Software or any product or circuit described in the Software. Cypress does
* not authorize its products for use in any products where a malfunction or
* failure of the Cypress product may reasonably be expected to result in
* significant property damage, injury or death (“High Risk Product”). By
* including Cypress’s product in a High Risk Product, the manufacturer of such
* system or application assumes all risk of such use and in doing so agrees to
* indemnify Cypress against all liability.
*******************************************************************************/

/*******************************************************************************
* Include guard
*******************************************************************************/
#ifndef SECURE_KEYS_H_
#define SECURE_KEYS_H_

/* HTTPS server certificate. Copy from the HTTPS server certificate
 * generated by OpenSSL (See Readme.md on how to generate a SSL certificate).
 */
#define keySERVER_CERTIFICATE_PEM \
"-----BEGIN CERTIFICATE-----\n"\
"MIID5DCCAsygAwIBAgIUMtOU0QhhuaJaCSavNGLH2c7Kf5YwDQYJKoZIhvcNAQEL\n"\
"BQAwezELMAkGA1UEBhMCSU4xEjAQBgNVBAgMCUthcm5hdGFrYTESMBAGA1UEBwwJ\n"\
"QmVuZ2FsdXJ1MQswCQYDVQQKDAJDWTEUMBIGA1UECwwLRW5naW5lZXJpbmcxITAf\n"\
"BgNVBAMMGG15c2VjdXJlaHR0cHNlcnZlci5sb2NhbDAeFw0yMDA2MjgwOTE1MzRa\n"\
"Fw0zMDA2MjYwOTE1MzRaMHsxCzAJBgNVBAYTAklOMRIwEAYDVQQIDAlLYXJuYXRh\n"\
"a2ExEjAQBgNVBAcMCUJlbmdhbHVydTELMAkGA1UECgwCQ1kxFDASBgNVBAsMC0Vu\n"\
"Z2luZWVyaW5nMSEwHwYDVQQDDBhteXNlY3VyZWh0dHBzZXJ2ZXIubG9jYWwwggEi\n"\
"MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDB2yIgT/9TAY1kpwC+NmNjJ0Pj\n"\
"bnTyrig34jiWX2sW/Qn9plyprmrhqoX8v/CD5zatpbd+fj8quVsfjHueP/BIgMZj\n"\
"s2Rt2Q7cTzMzgfhfY5n/Tg4B8L/cH5tQYwS1/SwouCpp1tioJLuvvVj2XBC76XUd\n"\
"ybyqQteIloALA5HFfjChrh1BaDM3bKIqhqW15lfRmDa50QAvq2+Tr6/zv0I3MP6x\n"\
"y2kaNRwebMSQipuOrFboEMc7fYl7V5rA6Rz3Ph3m3zXfFN+s7CWa9rkdsbfpXIfF\n"\
"lSoHVi/f/brlX7xNpDx8PYz1sX4nMHecniMEfBCoAWh19ypXBvF1YOsAGGtxAgMB\n"\
"AAGjYDBeMB8GA1UdIwQYMBaAFM6gm80hMJNIu/e4szg9d9YDnHivMAkGA1UdEwQC\n"\
"MAAwCwYDVR0PBAQDAgTwMCMGA1UdEQQcMBqCGG15c2VjdXJlaHR0cHNlcnZlci5s\n"\
"b2NhbDANBgkqhkiG9w0BAQsFAAOCAQEAM7u6dA/3Y9tHkgYY6f04VOBjIgUXRcto\n"\
"pWLh0MiQG41m+c9F0AJxaljY1BW6W21pQEIB2hV3I6/p70x2VC8cPks7RbE/8kjX\n"\
"k9P1ZgKvgaHpA1opjKDfpEs9E0Q57ycWNofFlkhytl02nyR30Uma65FXcdISSmcz\n"\
"SH5eGZSwZIF6yKpJomfTX711UeGMu8uF3EwsTappzyOCtgdBy5emEgC22Zq5Moeq\n"\
"zlDP/zz/xLtjpOHKMI0wERLQQ08GVtYIjCkA5u4FaF9fabFVEAJxDaKpIqxrBu3N\n"\
"PtB9swI5SFuVLX4g2tgfM5+QIv8aYV4QddHiOT19+AW56bY1C0ZzFA==\n"\
"-----END CERTIFICATE-----"

/* Private key of the HTTPS server. Copy from the HTTPS server key
 * generated by OpenSSL (See Readme.md on how to create a private key).
 */
#define keySERVER_PRIVATE_KEY_PEM \
"-----BEGIN RSA PRIVATE KEY-----\n"\
"MIIEpAIBAAKCAQEAwdsiIE//UwGNZKcAvjZjYydD42508q4oN+I4ll9rFv0J/aZc\n"\
"qa5q4aqF/L/wg+c2raW3fn4/KrlbH4x7nj/wSIDGY7NkbdkO3E8zM4H4X2OZ/04O\n"\
"AfC/3B+bUGMEtf0sKLgqadbYqCS7r71Y9lwQu+l1Hcm8qkLXiJaACwORxX4woa4d\n"\
"QWgzN2yiKoalteZX0Zg2udEAL6tvk6+v879CNzD+sctpGjUcHmzEkIqbjqxW6BDH\n"\
"O32Je1eawOkc9z4d5t813xTfrOwlmva5HbG36VyHxZUqB1Yv3/265V+8TaQ8fD2M\n"\
"9bF+JzB3nJ4jBHwQqAFodfcqVwbxdWDrABhrcQIDAQABAoIBACMGdb8C1S3pLOPP\n"\
"rLmxV/m1QXXZIjYqs0eNjw3URaQMqf5zTXC2+8a0KatF/q3GW8G6HFI1ezI79TPZ\n"\
"DQjFoqNm6PFgmzehrSavBKA8zmRluZBASRWeqvuZllVK3rIHATCGPduLnu+aW3Lg\n"\
"Mi+o6Lka8DcmmPjmRMz/7DiRN4hH+N8+OqPhQZNnYjUQ/cEvNkIeUtks4QNBc6G4\n"\
"VpoNtm9RgamwNFM54Um6uIqDw/MQwERiWzUWNRN4SIL3HRt5Uj41/aKaSmIYPpOU\n"\
"PZnDPOplGrwIEDL6hHcEjK0CFysgdD2iabOTK+NVDGk7pDNG9ynwZTNQkQQDBbDJ\n"\
"4I0eCAECgYEA6421/eh7gUCXf83YAku/hs/UeE5rCrIPo2t+i29Aasmxiruvk0LW\n"\
"pJZgCde2MnDL79GPFWcxhL5eXoxKsLvlhfFQ+wmhdSm+ygJaM04WxlUZjGWWGaZN\n"\
"PFzX1e0SS0M0Zn+E8k4i9Bhrdhig3TEXveqrKkYs5Qj8m1NVBAkE0/ECgYEA0q7Z\n"\
"7BAW+UCDgZvv+ivNBRTzTt9JSXsMIunc3JoFoWCoL2EQkjSLv9CbBmhlwB5QwOpN\n"\
"YjGp8/fbrmrkgzj68Vh2CmSCuSKhl8oaY6bP60u0hru2PleBuz77AeKZ7beprrlG\n"\
"W5yIj+1pXXrobAIQwM7bw4Wwy6NDyWRoMJSmj4ECgYEAo7ZpT6B9/jZTVUtOn0Hg\n"\
"SqU1qavu748UGWODnwtifRXTZHXPsIzau6eb9htLkUEeLH68cIa5PuZElnfxDWZ6\n"\
"Pp6axu9JnTG3XZVG9bOHVq8cw5xzNz6DHbn1dMSBW3fI+pgUYYf2+Snjvj+dxj3x\n"\
"n1hzQD1nxIN7dcT0KIrQJTECgYBkdpJeGdIKqzPKUySc49QQz0uyWZEl4/IGmAQE\n"\
"gcGbkW7BoQR442ucXQn/hTq34Pza8R9TaqFDP/bWdgxfcoVfHrKzA/i99YCe0/W/\n"\
"fST6a5A7Czm9ApdPRZoF7Rs/muvj8F9Xgg4wq6IpvFkmX9nDRyDOXGrQwBqr5yAz\n"\
"wj6mgQKBgQDUAsx2YcSf5FmIqYAXBC9izQD0qkNW2z5dEPpLGPwJ2S8V/RiXH5YQ\n"\
"LsK+/69tQOh+T45Py7VjWjiWZY7H1ovWZPNo2QhaQaFkKZ9iKPHoZNprlWqRJBtw\n"\
"I5OT5vaDg3uX5gerbls/1u8/Xb89KnFx8jNjKJXwoJsn+PVUumb8Ng==\n"\
"-----END RSA PRIVATE KEY-----"

/* HTTPS client certificate. In this example this is the RootCA
 * certificate so as to verify the HTTPS client's identity. */
#define keyCLIENT_ROOTCA_PEM \
"-----BEGIN CERTIFICATE-----\n"\
"MIID1zCCAr+gAwIBAgIUUDRmSHP1Av8oWSx6yNMIH91WeOkwDQYJKoZIhvcNAQEL\n"\
"BQAwezELMAkGA1UEBhMCSU4xEjAQBgNVBAgMCUthcm5hdGFrYTESMBAGA1UEBwwJ\n"\
"QmVuZ2FsdXJ1MQswCQYDVQQKDAJDWTEUMBIGA1UECwwLRW5naW5lZXJpbmcxITAf\n"\
"BgNVBAMMGG15c2VjdXJlaHR0cHNlcnZlci5sb2NhbDAeFw0yMDA2MjgwOTE1MzNa\n"\
"Fw0zMDA2MjYwOTE1MzNaMHsxCzAJBgNVBAYTAklOMRIwEAYDVQQIDAlLYXJuYXRh\n"\
"a2ExEjAQBgNVBAcMCUJlbmdhbHVydTELMAkGA1UECgwCQ1kxFDASBgNVBAsMC0Vu\n"\
"Z2luZWVyaW5nMSEwHwYDVQQDDBhteXNlY3VyZWh0dHBzZXJ2ZXIubG9jYWwwggEi\n"\
"MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDimP0kV5vLRyzpiSEZpAwNYoTo\n"\
"/wxgkY3gMWpLnVPxu624q50sXTAYCAxbZdZL5qfptfaksEDd5vXreNol6ck+RwNP\n"\
"R+XKSF8+VfZeXnXGn0XDq4vLY3oInqkiMpfd7UwyS/9X6UUz6Nb2+p7U4lrcbjwN\n"\
"7R8OeqXt11k9wd1FzCF8vSsnjXZDLdmN5VL4x1P0KbphipNFzz/ASrkx0fWh3cEg\n"\
"0OLvrGdW7K/mtXpXM7q7onAQdrQIw3zSC/DtStCpTmO1zSMsjv+lfYhIIXI5j3VH\n"\
"zaRmx3cHlcttFVEwuWA0GN15Kb5x69mGuGlRr09dIUil9Tv22i95xUROwG8NAgMB\n"\
"AAGjUzBRMB0GA1UdDgQWBBTOoJvNITCTSLv3uLM4PXfWA5x4rzAfBgNVHSMEGDAW\n"\
"gBTOoJvNITCTSLv3uLM4PXfWA5x4rzAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3\n"\
"DQEBCwUAA4IBAQBtHSxvG6nk/hUA3Ta7fU1z6R4Tf+nnlwprtKVhczvTQlybFUqk\n"\
"SZbGwc8G/jUHy5fyGDHsMRoUwz5PBPhPOHwfzOUGpudeFfhdBG/OWqoKLVvxolHP\n"\
"U9fxr+59Cm1wScvxwzZeISsRfl4TPlUfRsheM1mT2WDB8kbYhzx/lZP+2qixxX/2\n"\
"Zp/zQfXplvKtUY2sN0WFepdIyvSzXLXouD+I/h/WnvSnchwLdzRuY6mDaJbWE7S3\n"\
"wqqyYyV+F5fNqEB1m9MHZ3+HKIelN3dTDp9U21x2Vsy6giqakj9SH6chJCi5VCwn\n"\
"sYcfZu8PTNQK9iuED+y570tns/51T+bXoKs+\n"\
"-----END CERTIFICATE-----"

#endif /* SECURE_KEYS_H_ */


/* [] END OF FILE */

